//*****************************************************************************
//*****************************************************************************
//  FILENAME: CYFISNP_Private.h
//  Version: 2.00, Updated on 2011/6/28 at 6:7:54
//  Generated by PSoC Designer 5.1.2306
//
//  DESCRIPTION: <NODE> Star Network Protocol Header file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#ifndef CYFISNP_PRIVATE_H
#define CYFISNP_PRIVATE_H

#include <m8c.h>

#include "CYFISNP_Protocol.h"

#define CYFISNP_SPI_BITRATE		   0x1
#define CYFISNP_CPU_CYCLES_PER_BYTE   0x40
#define CYFISNP_CPU_CLK               0xc

// ---------------------------------------------------------------------------
// If External PA used, need wider guard band, so increase margins.
// The physical Tx frequency is 2 MHz HIGHER than what is stored here.
// ---------------------------------------------------------------------------
#define CYFISNP_CHAN_MIN 0xa
#define CYFISNP_CHAN_MAX 0x3a

#define CYFISNP_MAX_CHANNELS    78 // 6 sets * 13 ch = 78 ch total


#define CYFISNP_SIZEOF_MID  4


// ---------------------------------------------------------------------------
//
// Private variables (start with lower-case letter following underscore)
//
// ---------------------------------------------------------------------------






// ---------------------------------------------------------------------------
// DEBUG ONLY
// ---------------------------------------------------------------------------
#if defined CYFISNP_DEBUG
    void    CYFISNP_OutChar     (unsigned char data);
    void    CYFISNP_OutStr      (const unsigned char *pbStrPtr);
    void    CYFISNP_OutHex      (char data);
    void    CYFISNP_OutNibble   (char data);
#else
    #define CYFISNP_OutChar(dummy)
    #define CYFISNP_OutStr(dummy)
    #define CYFISNP_OutHex(dummy)
    #define CYFISNP_OutNibble(dummy)
#endif

#endif  // CYFISNP_PRIVATE_H
// ###########################################################################
