//*****************************************************************************
//*****************************************************************************
//  FILENAME: CYFISNP_Eeprom.h
//  Version: 2.00, Updated on 2011/6/28 at 6:7:54
//  Generated by PSoC Designer 5.1.2306
//
//  DESCRIPTION: Star Network Protocol NODE EEPROM structures
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#ifndef CYFISNP_EPROM_H_
#define CYFISNP_EPROM_H_

#include <m8c.h>

#include "CYFISNP_Private.h"

// ---------------------------------------------------------------------------
#define CYFISNP_EEP_NET_REC_ADR ((CYFISNP_EEP_NET_REC const *)(CYFISNP_EEP_PHY_ADR))

// ---------------------------------------------------------------------------
//
// CYFISNP_EEP_NET_REC - Hub or Node EEPROM Network Parameter Record
//
// ---------------------------------------------------------------------------
typedef struct {                // -------------------------------------------
    BYTE sopIdx;                //
    BYTE chBase;                //
    BYTE chHop;                 //
    BYTE hubSeedMsb;            // Hub CRC Seed[15:8]
    BYTE hubSeedLsb;            // Hub CRC Seed[ 7:0]
                                // -------------------------------------------
    BYTE devId;                 // only used by Nodes
    BYTE nodeSeedMsb;           // used only by Nodes
    BYTE nodeSeedLsb;           // used only by Nodes
} CYFISNP_EEP_NET_REC;              // -------------------------------------------
// ---------------------------------------------------------------------------
// EXAMPLE USEAGE
//    CYFISNP_EEP_NET_REC net;
//    net.sopIdx     = 0xDE;
//    net.chBase     = 0xAD;
//    net.chHop      = 0x55;
//    net.hubSeedMsb = 0xBE;
//    net.hubSeedLsb = 0xEF;
//    net.devId      = 0xA5;
//    retval = E2PROM_bE2Write( (WORD) CYFISNP_EEP_NET_REC_ADR,
//                              (BYTE*) &net,
//                              (BYTE)sizeof(CYFISNP_EEP_NET_REC), 25);
// ---------------------------------------------------------------------------

#endif  // CYFISNP_EPROM_H_
// ###########################################################################
