/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#include <m8c.h>
// ChipSelect address and mask defines
#pragma	ioport	ChipSelect_Data_ADDR:	0x0
BYTE			ChipSelect_Data_ADDR;
#pragma	ioport	ChipSelect_DriveMode_0_ADDR:	0x100
BYTE			ChipSelect_DriveMode_0_ADDR;
#pragma	ioport	ChipSelect_DriveMode_1_ADDR:	0x101
BYTE			ChipSelect_DriveMode_1_ADDR;
#pragma	ioport	ChipSelect_DriveMode_2_ADDR:	0x3
BYTE			ChipSelect_DriveMode_2_ADDR;
#pragma	ioport	ChipSelect_GlobalSelect_ADDR:	0x2
BYTE			ChipSelect_GlobalSelect_ADDR;
#pragma	ioport	ChipSelect_IntCtrl_0_ADDR:	0x102
BYTE			ChipSelect_IntCtrl_0_ADDR;
#pragma	ioport	ChipSelect_IntCtrl_1_ADDR:	0x103
BYTE			ChipSelect_IntCtrl_1_ADDR;
#pragma	ioport	ChipSelect_IntEn_ADDR:	0x1
BYTE			ChipSelect_IntEn_ADDR;
#define ChipSelect_MASK 0x4
// DataReady address and mask defines
#pragma	ioport	DataReady_Data_ADDR:	0x0
BYTE			DataReady_Data_ADDR;
#pragma	ioport	DataReady_DriveMode_0_ADDR:	0x100
BYTE			DataReady_DriveMode_0_ADDR;
#pragma	ioport	DataReady_DriveMode_1_ADDR:	0x101
BYTE			DataReady_DriveMode_1_ADDR;
#pragma	ioport	DataReady_DriveMode_2_ADDR:	0x3
BYTE			DataReady_DriveMode_2_ADDR;
#pragma	ioport	DataReady_GlobalSelect_ADDR:	0x2
BYTE			DataReady_GlobalSelect_ADDR;
#pragma	ioport	DataReady_IntCtrl_0_ADDR:	0x102
BYTE			DataReady_IntCtrl_0_ADDR;
#pragma	ioport	DataReady_IntCtrl_1_ADDR:	0x103
BYTE			DataReady_IntCtrl_1_ADDR;
#pragma	ioport	DataReady_IntEn_ADDR:	0x1
BYTE			DataReady_IntEn_ADDR;
#define DataReady_MASK 0x8
// RedLED address and mask defines
#pragma	ioport	RedLED_Data_ADDR:	0x4
BYTE			RedLED_Data_ADDR;
#pragma	ioport	RedLED_DriveMode_0_ADDR:	0x104
BYTE			RedLED_DriveMode_0_ADDR;
#pragma	ioport	RedLED_DriveMode_1_ADDR:	0x105
BYTE			RedLED_DriveMode_1_ADDR;
#pragma	ioport	RedLED_DriveMode_2_ADDR:	0x7
BYTE			RedLED_DriveMode_2_ADDR;
#pragma	ioport	RedLED_GlobalSelect_ADDR:	0x6
BYTE			RedLED_GlobalSelect_ADDR;
#pragma	ioport	RedLED_IntCtrl_0_ADDR:	0x106
BYTE			RedLED_IntCtrl_0_ADDR;
#pragma	ioport	RedLED_IntCtrl_1_ADDR:	0x107
BYTE			RedLED_IntCtrl_1_ADDR;
#pragma	ioport	RedLED_IntEn_ADDR:	0x5
BYTE			RedLED_IntEn_ADDR;
#define RedLED_MASK 0x4
// GreenLED address and mask defines
#pragma	ioport	GreenLED_Data_ADDR:	0x4
BYTE			GreenLED_Data_ADDR;
#pragma	ioport	GreenLED_DriveMode_0_ADDR:	0x104
BYTE			GreenLED_DriveMode_0_ADDR;
#pragma	ioport	GreenLED_DriveMode_1_ADDR:	0x105
BYTE			GreenLED_DriveMode_1_ADDR;
#pragma	ioport	GreenLED_DriveMode_2_ADDR:	0x7
BYTE			GreenLED_DriveMode_2_ADDR;
#pragma	ioport	GreenLED_GlobalSelect_ADDR:	0x6
BYTE			GreenLED_GlobalSelect_ADDR;
#pragma	ioport	GreenLED_IntCtrl_0_ADDR:	0x106
BYTE			GreenLED_IntCtrl_0_ADDR;
#pragma	ioport	GreenLED_IntCtrl_1_ADDR:	0x107
BYTE			GreenLED_IntCtrl_1_ADDR;
#pragma	ioport	GreenLED_IntEn_ADDR:	0x5
BYTE			GreenLED_IntEn_ADDR;
#define GreenLED_MASK 0x8
// SW2 address and mask defines
#pragma	ioport	SW2_Data_ADDR:	0x4
BYTE			SW2_Data_ADDR;
#pragma	ioport	SW2_DriveMode_0_ADDR:	0x104
BYTE			SW2_DriveMode_0_ADDR;
#pragma	ioport	SW2_DriveMode_1_ADDR:	0x105
BYTE			SW2_DriveMode_1_ADDR;
#pragma	ioport	SW2_DriveMode_2_ADDR:	0x7
BYTE			SW2_DriveMode_2_ADDR;
#pragma	ioport	SW2_GlobalSelect_ADDR:	0x6
BYTE			SW2_GlobalSelect_ADDR;
#pragma	ioport	SW2_IntCtrl_0_ADDR:	0x106
BYTE			SW2_IntCtrl_0_ADDR;
#pragma	ioport	SW2_IntCtrl_1_ADDR:	0x107
BYTE			SW2_IntCtrl_1_ADDR;
#pragma	ioport	SW2_IntEn_ADDR:	0x5
BYTE			SW2_IntEn_ADDR;
#define SW2_MASK 0x10
// I2CSDA address and mask defines
#pragma	ioport	I2CSDA_Data_ADDR:	0x4
BYTE			I2CSDA_Data_ADDR;
#pragma	ioport	I2CSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CSDA_IntEn_ADDR:	0x5
BYTE			I2CSDA_IntEn_ADDR;
#define I2CSDA_MASK 0x20
// SW1 address and mask defines
#pragma	ioport	SW1_Data_ADDR:	0x4
BYTE			SW1_Data_ADDR;
#pragma	ioport	SW1_DriveMode_0_ADDR:	0x104
BYTE			SW1_DriveMode_0_ADDR;
#pragma	ioport	SW1_DriveMode_1_ADDR:	0x105
BYTE			SW1_DriveMode_1_ADDR;
#pragma	ioport	SW1_DriveMode_2_ADDR:	0x7
BYTE			SW1_DriveMode_2_ADDR;
#pragma	ioport	SW1_GlobalSelect_ADDR:	0x6
BYTE			SW1_GlobalSelect_ADDR;
#pragma	ioport	SW1_IntCtrl_0_ADDR:	0x106
BYTE			SW1_IntCtrl_0_ADDR;
#pragma	ioport	SW1_IntCtrl_1_ADDR:	0x107
BYTE			SW1_IntCtrl_1_ADDR;
#pragma	ioport	SW1_IntEn_ADDR:	0x5
BYTE			SW1_IntEn_ADDR;
#define SW1_MASK 0x40
// I2CSCL address and mask defines
#pragma	ioport	I2CSCL_Data_ADDR:	0x4
BYTE			I2CSCL_Data_ADDR;
#pragma	ioport	I2CSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CSCL_IntEn_ADDR:	0x5
BYTE			I2CSCL_IntEn_ADDR;
#define I2CSCL_MASK 0x80
// LP_MISO address and mask defines
#pragma	ioport	LP_MISO_Data_ADDR:	0x8
BYTE			LP_MISO_Data_ADDR;
#pragma	ioport	LP_MISO_DriveMode_0_ADDR:	0x108
BYTE			LP_MISO_DriveMode_0_ADDR;
#pragma	ioport	LP_MISO_DriveMode_1_ADDR:	0x109
BYTE			LP_MISO_DriveMode_1_ADDR;
#pragma	ioport	LP_MISO_DriveMode_2_ADDR:	0xb
BYTE			LP_MISO_DriveMode_2_ADDR;
#pragma	ioport	LP_MISO_GlobalSelect_ADDR:	0xa
BYTE			LP_MISO_GlobalSelect_ADDR;
#pragma	ioport	LP_MISO_IntCtrl_0_ADDR:	0x10a
BYTE			LP_MISO_IntCtrl_0_ADDR;
#pragma	ioport	LP_MISO_IntCtrl_1_ADDR:	0x10b
BYTE			LP_MISO_IntCtrl_1_ADDR;
#pragma	ioport	LP_MISO_IntEn_ADDR:	0x9
BYTE			LP_MISO_IntEn_ADDR;
#define LP_MISO_MASK 0x1
// LP_MISO Shadow defines
//   LP_MISO_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LP_MISO_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LP_SCK address and mask defines
#pragma	ioport	LP_SCK_Data_ADDR:	0x8
BYTE			LP_SCK_Data_ADDR;
#pragma	ioport	LP_SCK_DriveMode_0_ADDR:	0x108
BYTE			LP_SCK_DriveMode_0_ADDR;
#pragma	ioport	LP_SCK_DriveMode_1_ADDR:	0x109
BYTE			LP_SCK_DriveMode_1_ADDR;
#pragma	ioport	LP_SCK_DriveMode_2_ADDR:	0xb
BYTE			LP_SCK_DriveMode_2_ADDR;
#pragma	ioport	LP_SCK_GlobalSelect_ADDR:	0xa
BYTE			LP_SCK_GlobalSelect_ADDR;
#pragma	ioport	LP_SCK_IntCtrl_0_ADDR:	0x10a
BYTE			LP_SCK_IntCtrl_0_ADDR;
#pragma	ioport	LP_SCK_IntCtrl_1_ADDR:	0x10b
BYTE			LP_SCK_IntCtrl_1_ADDR;
#pragma	ioport	LP_SCK_IntEn_ADDR:	0x9
BYTE			LP_SCK_IntEn_ADDR;
#define LP_SCK_MASK 0x8
// LP_SCK Shadow defines
//   LP_SCK_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LP_SCK_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LP_MOSI address and mask defines
#pragma	ioport	LP_MOSI_Data_ADDR:	0x8
BYTE			LP_MOSI_Data_ADDR;
#pragma	ioport	LP_MOSI_DriveMode_0_ADDR:	0x108
BYTE			LP_MOSI_DriveMode_0_ADDR;
#pragma	ioport	LP_MOSI_DriveMode_1_ADDR:	0x109
BYTE			LP_MOSI_DriveMode_1_ADDR;
#pragma	ioport	LP_MOSI_DriveMode_2_ADDR:	0xb
BYTE			LP_MOSI_DriveMode_2_ADDR;
#pragma	ioport	LP_MOSI_GlobalSelect_ADDR:	0xa
BYTE			LP_MOSI_GlobalSelect_ADDR;
#pragma	ioport	LP_MOSI_IntCtrl_0_ADDR:	0x10a
BYTE			LP_MOSI_IntCtrl_0_ADDR;
#pragma	ioport	LP_MOSI_IntCtrl_1_ADDR:	0x10b
BYTE			LP_MOSI_IntCtrl_1_ADDR;
#pragma	ioport	LP_MOSI_IntEn_ADDR:	0x9
BYTE			LP_MOSI_IntEn_ADDR;
#define LP_MOSI_MASK 0x20
// LP_MOSI Shadow defines
//   LP_MOSI_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LP_MOSI_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CYFISNP_IRQ address and mask defines
#pragma	ioport	CYFISNP_IRQ_Data_ADDR:	0x8
BYTE			CYFISNP_IRQ_Data_ADDR;
#pragma	ioport	CYFISNP_IRQ_DriveMode_0_ADDR:	0x108
BYTE			CYFISNP_IRQ_DriveMode_0_ADDR;
#pragma	ioport	CYFISNP_IRQ_DriveMode_1_ADDR:	0x109
BYTE			CYFISNP_IRQ_DriveMode_1_ADDR;
#pragma	ioport	CYFISNP_IRQ_DriveMode_2_ADDR:	0xb
BYTE			CYFISNP_IRQ_DriveMode_2_ADDR;
#pragma	ioport	CYFISNP_IRQ_GlobalSelect_ADDR:	0xa
BYTE			CYFISNP_IRQ_GlobalSelect_ADDR;
#pragma	ioport	CYFISNP_IRQ_IntCtrl_0_ADDR:	0x10a
BYTE			CYFISNP_IRQ_IntCtrl_0_ADDR;
#pragma	ioport	CYFISNP_IRQ_IntCtrl_1_ADDR:	0x10b
BYTE			CYFISNP_IRQ_IntCtrl_1_ADDR;
#pragma	ioport	CYFISNP_IRQ_IntEn_ADDR:	0x9
BYTE			CYFISNP_IRQ_IntEn_ADDR;
#define CYFISNP_IRQ_MASK 0x40
// CYFISNP_IRQ Shadow defines
//   CYFISNP_IRQ_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CYFISNP_IRQ_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CYFISNP_nSS address and mask defines
#pragma	ioport	CYFISNP_nSS_Data_ADDR:	0x8
BYTE			CYFISNP_nSS_Data_ADDR;
#pragma	ioport	CYFISNP_nSS_DriveMode_0_ADDR:	0x108
BYTE			CYFISNP_nSS_DriveMode_0_ADDR;
#pragma	ioport	CYFISNP_nSS_DriveMode_1_ADDR:	0x109
BYTE			CYFISNP_nSS_DriveMode_1_ADDR;
#pragma	ioport	CYFISNP_nSS_DriveMode_2_ADDR:	0xb
BYTE			CYFISNP_nSS_DriveMode_2_ADDR;
#pragma	ioport	CYFISNP_nSS_GlobalSelect_ADDR:	0xa
BYTE			CYFISNP_nSS_GlobalSelect_ADDR;
#pragma	ioport	CYFISNP_nSS_IntCtrl_0_ADDR:	0x10a
BYTE			CYFISNP_nSS_IntCtrl_0_ADDR;
#pragma	ioport	CYFISNP_nSS_IntCtrl_1_ADDR:	0x10b
BYTE			CYFISNP_nSS_IntCtrl_1_ADDR;
#pragma	ioport	CYFISNP_nSS_IntEn_ADDR:	0x9
BYTE			CYFISNP_nSS_IntEn_ADDR;
#define CYFISNP_nSS_MASK 0x80
// CYFISNP_nSS Shadow defines
//   CYFISNP_nSS_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CYFISNP_nSS_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
