/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// CSDCapacitor address and mask defines
#pragma	ioport	CSDCapacitor_Data_ADDR:	0x0
BYTE			CSDCapacitor_Data_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_0_ADDR:	0x100
BYTE			CSDCapacitor_DriveMode_0_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_1_ADDR:	0x101
BYTE			CSDCapacitor_DriveMode_1_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_2_ADDR:	0x3
BYTE			CSDCapacitor_DriveMode_2_ADDR;
#pragma	ioport	CSDCapacitor_GlobalSelect_ADDR:	0x2
BYTE			CSDCapacitor_GlobalSelect_ADDR;
#pragma	ioport	CSDCapacitor_IntCtrl_0_ADDR:	0x102
BYTE			CSDCapacitor_IntCtrl_0_ADDR;
#pragma	ioport	CSDCapacitor_IntCtrl_1_ADDR:	0x103
BYTE			CSDCapacitor_IntCtrl_1_ADDR;
#pragma	ioport	CSDCapacitor_IntEn_ADDR:	0x1
BYTE			CSDCapacitor_IntEn_ADDR;
#define CSDCapacitor_MASK 0x2
#pragma	ioport	CSDCapacitor_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDCapacitor_MUXBusCtrl_ADDR;
// LED_BLUEPin address and mask defines
#pragma	ioport	LED_BLUEPin_Data_ADDR:	0x4
BYTE			LED_BLUEPin_Data_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_0_ADDR:	0x104
BYTE			LED_BLUEPin_DriveMode_0_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_1_ADDR:	0x105
BYTE			LED_BLUEPin_DriveMode_1_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_2_ADDR:	0x7
BYTE			LED_BLUEPin_DriveMode_2_ADDR;
#pragma	ioport	LED_BLUEPin_GlobalSelect_ADDR:	0x6
BYTE			LED_BLUEPin_GlobalSelect_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_BLUEPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_BLUEPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_BLUEPin_IntEn_ADDR:	0x5
BYTE			LED_BLUEPin_IntEn_ADDR;
#define LED_BLUEPin_MASK 0x4
#pragma	ioport	LED_BLUEPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_BLUEPin_MUXBusCtrl_ADDR;
// LED_BLUEPin Shadow defines
//   LED_BLUEPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_BLUEPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_REDPin address and mask defines
#pragma	ioport	LED_REDPin_Data_ADDR:	0x4
BYTE			LED_REDPin_Data_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_0_ADDR:	0x104
BYTE			LED_REDPin_DriveMode_0_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_1_ADDR:	0x105
BYTE			LED_REDPin_DriveMode_1_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_2_ADDR:	0x7
BYTE			LED_REDPin_DriveMode_2_ADDR;
#pragma	ioport	LED_REDPin_GlobalSelect_ADDR:	0x6
BYTE			LED_REDPin_GlobalSelect_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_REDPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_REDPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_REDPin_IntEn_ADDR:	0x5
BYTE			LED_REDPin_IntEn_ADDR;
#define LED_REDPin_MASK 0x8
#pragma	ioport	LED_REDPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_REDPin_MUXBusCtrl_ADDR;
// LED_REDPin Shadow defines
//   LED_REDPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_REDPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_GREENPin address and mask defines
#pragma	ioport	LED_GREENPin_Data_ADDR:	0x4
BYTE			LED_GREENPin_Data_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_0_ADDR:	0x104
BYTE			LED_GREENPin_DriveMode_0_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_1_ADDR:	0x105
BYTE			LED_GREENPin_DriveMode_1_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_2_ADDR:	0x7
BYTE			LED_GREENPin_DriveMode_2_ADDR;
#pragma	ioport	LED_GREENPin_GlobalSelect_ADDR:	0x6
BYTE			LED_GREENPin_GlobalSelect_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_GREENPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_GREENPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_GREENPin_IntEn_ADDR:	0x5
BYTE			LED_GREENPin_IntEn_ADDR;
#define LED_GREENPin_MASK 0x10
#pragma	ioport	LED_GREENPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_GREENPin_MUXBusCtrl_ADDR;
// LED_GREENPin Shadow defines
//   LED_GREENPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_GREENPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSDSW0 address and mask defines
#pragma	ioport	CSDSW0_Data_ADDR:	0x8
BYTE			CSDSW0_Data_ADDR;
#pragma	ioport	CSDSW0_DriveMode_0_ADDR:	0x108
BYTE			CSDSW0_DriveMode_0_ADDR;
#pragma	ioport	CSDSW0_DriveMode_1_ADDR:	0x109
BYTE			CSDSW0_DriveMode_1_ADDR;
#pragma	ioport	CSDSW0_DriveMode_2_ADDR:	0xb
BYTE			CSDSW0_DriveMode_2_ADDR;
#pragma	ioport	CSDSW0_GlobalSelect_ADDR:	0xa
BYTE			CSDSW0_GlobalSelect_ADDR;
#pragma	ioport	CSDSW0_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW0_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW0_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW0_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW0_IntEn_ADDR:	0x9
BYTE			CSDSW0_IntEn_ADDR;
#define CSDSW0_MASK 0x1
#pragma	ioport	CSDSW0_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW0_MUXBusCtrl_ADDR;
// CSDSW0 Shadow defines
//   CSDSW0_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW0_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDResistor address and mask defines
#pragma	ioport	CSDResistor_Data_ADDR:	0xc
BYTE			CSDResistor_Data_ADDR;
#pragma	ioport	CSDResistor_DriveMode_0_ADDR:	0x10c
BYTE			CSDResistor_DriveMode_0_ADDR;
#pragma	ioport	CSDResistor_DriveMode_1_ADDR:	0x10d
BYTE			CSDResistor_DriveMode_1_ADDR;
#pragma	ioport	CSDResistor_DriveMode_2_ADDR:	0xf
BYTE			CSDResistor_DriveMode_2_ADDR;
#pragma	ioport	CSDResistor_GlobalSelect_ADDR:	0xe
BYTE			CSDResistor_GlobalSelect_ADDR;
#pragma	ioport	CSDResistor_IntCtrl_0_ADDR:	0x10e
BYTE			CSDResistor_IntCtrl_0_ADDR;
#pragma	ioport	CSDResistor_IntCtrl_1_ADDR:	0x10f
BYTE			CSDResistor_IntCtrl_1_ADDR;
#pragma	ioport	CSDResistor_IntEn_ADDR:	0xd
BYTE			CSDResistor_IntEn_ADDR;
#define CSDResistor_MASK 0x2
#pragma	ioport	CSDResistor_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDResistor_MUXBusCtrl_ADDR;
