//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_BLUE.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_BLUE User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_BLUE_INCLUDE
#define LED_BLUE_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_BLUE_Stop
#pragma fastcall16  LED_BLUE_Start
#pragma fastcall16  LED_BLUE_On
#pragma fastcall16  LED_BLUE_Off
#pragma fastcall16  LED_BLUE_Switch
#pragma fastcall16  LED_BLUE_Invert
#pragma fastcall16  LED_BLUE_GetState


//-------------------------------------------------
// Constants for LED_BLUE API's.
//-------------------------------------------------
//
#define  LED_BLUE_ON   1
#define  LED_BLUE_OFF  0

//-------------------------------------------------
// Prototypes of the LED_BLUE API.
//-------------------------------------------------
extern void  LED_BLUE_Start(void);                                     
extern void  LED_BLUE_Stop(void);                                      
extern void  LED_BLUE_On(void);                                      
extern void  LED_BLUE_Off(void);                                      
extern void  LED_BLUE_Switch(BYTE bSwitch);
extern void  LED_BLUE_Invert(void);                                         
extern BYTE  LED_BLUE_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
