/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// CSDCapacitor address and mask defines
#pragma	ioport	CSDCapacitor_Data_ADDR:	0x0
BYTE			CSDCapacitor_Data_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_0_ADDR:	0x100
BYTE			CSDCapacitor_DriveMode_0_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_1_ADDR:	0x101
BYTE			CSDCapacitor_DriveMode_1_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_2_ADDR:	0x3
BYTE			CSDCapacitor_DriveMode_2_ADDR;
#pragma	ioport	CSDCapacitor_GlobalSelect_ADDR:	0x2
BYTE			CSDCapacitor_GlobalSelect_ADDR;
#pragma	ioport	CSDCapacitor_IntCtrl_0_ADDR:	0x102
BYTE			CSDCapacitor_IntCtrl_0_ADDR;
#pragma	ioport	CSDCapacitor_IntCtrl_1_ADDR:	0x103
BYTE			CSDCapacitor_IntCtrl_1_ADDR;
#pragma	ioport	CSDCapacitor_IntEn_ADDR:	0x1
BYTE			CSDCapacitor_IntEn_ADDR;
#define CSDCapacitor_MASK 0x2
#pragma	ioport	CSDCapacitor_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDCapacitor_MUXBusCtrl_ADDR;
// LED_BLUEPin address and mask defines
#pragma	ioport	LED_BLUEPin_Data_ADDR:	0x4
BYTE			LED_BLUEPin_Data_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_0_ADDR:	0x104
BYTE			LED_BLUEPin_DriveMode_0_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_1_ADDR:	0x105
BYTE			LED_BLUEPin_DriveMode_1_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_2_ADDR:	0x7
BYTE			LED_BLUEPin_DriveMode_2_ADDR;
#pragma	ioport	LED_BLUEPin_GlobalSelect_ADDR:	0x6
BYTE			LED_BLUEPin_GlobalSelect_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_BLUEPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_BLUEPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_BLUEPin_IntEn_ADDR:	0x5
BYTE			LED_BLUEPin_IntEn_ADDR;
#define LED_BLUEPin_MASK 0x4
#pragma	ioport	LED_BLUEPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_BLUEPin_MUXBusCtrl_ADDR;
// LED_BLUEPin Shadow defines
//   LED_BLUEPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_BLUEPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_REDPin address and mask defines
#pragma	ioport	LED_REDPin_Data_ADDR:	0x4
BYTE			LED_REDPin_Data_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_0_ADDR:	0x104
BYTE			LED_REDPin_DriveMode_0_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_1_ADDR:	0x105
BYTE			LED_REDPin_DriveMode_1_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_2_ADDR:	0x7
BYTE			LED_REDPin_DriveMode_2_ADDR;
#pragma	ioport	LED_REDPin_GlobalSelect_ADDR:	0x6
BYTE			LED_REDPin_GlobalSelect_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_REDPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_REDPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_REDPin_IntEn_ADDR:	0x5
BYTE			LED_REDPin_IntEn_ADDR;
#define LED_REDPin_MASK 0x8
#pragma	ioport	LED_REDPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_REDPin_MUXBusCtrl_ADDR;
// LED_REDPin Shadow defines
//   LED_REDPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_REDPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_GREENPin address and mask defines
#pragma	ioport	LED_GREENPin_Data_ADDR:	0x4
BYTE			LED_GREENPin_Data_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_0_ADDR:	0x104
BYTE			LED_GREENPin_DriveMode_0_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_1_ADDR:	0x105
BYTE			LED_GREENPin_DriveMode_1_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_2_ADDR:	0x7
BYTE			LED_GREENPin_DriveMode_2_ADDR;
#pragma	ioport	LED_GREENPin_GlobalSelect_ADDR:	0x6
BYTE			LED_GREENPin_GlobalSelect_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_GREENPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_GREENPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_GREENPin_IntEn_ADDR:	0x5
BYTE			LED_GREENPin_IntEn_ADDR;
#define LED_GREENPin_MASK 0x10
#pragma	ioport	LED_GREENPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_GREENPin_MUXBusCtrl_ADDR;
// LED_GREENPin Shadow defines
//   LED_GREENPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_GREENPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSDSW0 address and mask defines
#pragma	ioport	CSDSW0_Data_ADDR:	0x8
BYTE			CSDSW0_Data_ADDR;
#pragma	ioport	CSDSW0_DriveMode_0_ADDR:	0x108
BYTE			CSDSW0_DriveMode_0_ADDR;
#pragma	ioport	CSDSW0_DriveMode_1_ADDR:	0x109
BYTE			CSDSW0_DriveMode_1_ADDR;
#pragma	ioport	CSDSW0_DriveMode_2_ADDR:	0xb
BYTE			CSDSW0_DriveMode_2_ADDR;
#pragma	ioport	CSDSW0_GlobalSelect_ADDR:	0xa
BYTE			CSDSW0_GlobalSelect_ADDR;
#pragma	ioport	CSDSW0_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW0_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW0_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW0_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW0_IntEn_ADDR:	0x9
BYTE			CSDSW0_IntEn_ADDR;
#define CSDSW0_MASK 0x1
#pragma	ioport	CSDSW0_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW0_MUXBusCtrl_ADDR;
// CSDSW0 Shadow defines
//   CSDSW0_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW0_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW1 address and mask defines
#pragma	ioport	CSDSW1_Data_ADDR:	0x8
BYTE			CSDSW1_Data_ADDR;
#pragma	ioport	CSDSW1_DriveMode_0_ADDR:	0x108
BYTE			CSDSW1_DriveMode_0_ADDR;
#pragma	ioport	CSDSW1_DriveMode_1_ADDR:	0x109
BYTE			CSDSW1_DriveMode_1_ADDR;
#pragma	ioport	CSDSW1_DriveMode_2_ADDR:	0xb
BYTE			CSDSW1_DriveMode_2_ADDR;
#pragma	ioport	CSDSW1_GlobalSelect_ADDR:	0xa
BYTE			CSDSW1_GlobalSelect_ADDR;
#pragma	ioport	CSDSW1_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW1_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW1_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW1_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW1_IntEn_ADDR:	0x9
BYTE			CSDSW1_IntEn_ADDR;
#define CSDSW1_MASK 0x2
#pragma	ioport	CSDSW1_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW1_MUXBusCtrl_ADDR;
// CSDSW1 Shadow defines
//   CSDSW1_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW1_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW2 address and mask defines
#pragma	ioport	CSDSW2_Data_ADDR:	0x8
BYTE			CSDSW2_Data_ADDR;
#pragma	ioport	CSDSW2_DriveMode_0_ADDR:	0x108
BYTE			CSDSW2_DriveMode_0_ADDR;
#pragma	ioport	CSDSW2_DriveMode_1_ADDR:	0x109
BYTE			CSDSW2_DriveMode_1_ADDR;
#pragma	ioport	CSDSW2_DriveMode_2_ADDR:	0xb
BYTE			CSDSW2_DriveMode_2_ADDR;
#pragma	ioport	CSDSW2_GlobalSelect_ADDR:	0xa
BYTE			CSDSW2_GlobalSelect_ADDR;
#pragma	ioport	CSDSW2_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW2_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW2_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW2_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW2_IntEn_ADDR:	0x9
BYTE			CSDSW2_IntEn_ADDR;
#define CSDSW2_MASK 0x4
#pragma	ioport	CSDSW2_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW2_MUXBusCtrl_ADDR;
// CSDSW2 Shadow defines
//   CSDSW2_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW2_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW3 address and mask defines
#pragma	ioport	CSDSW3_Data_ADDR:	0x8
BYTE			CSDSW3_Data_ADDR;
#pragma	ioport	CSDSW3_DriveMode_0_ADDR:	0x108
BYTE			CSDSW3_DriveMode_0_ADDR;
#pragma	ioport	CSDSW3_DriveMode_1_ADDR:	0x109
BYTE			CSDSW3_DriveMode_1_ADDR;
#pragma	ioport	CSDSW3_DriveMode_2_ADDR:	0xb
BYTE			CSDSW3_DriveMode_2_ADDR;
#pragma	ioport	CSDSW3_GlobalSelect_ADDR:	0xa
BYTE			CSDSW3_GlobalSelect_ADDR;
#pragma	ioport	CSDSW3_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW3_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW3_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW3_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW3_IntEn_ADDR:	0x9
BYTE			CSDSW3_IntEn_ADDR;
#define CSDSW3_MASK 0x8
#pragma	ioport	CSDSW3_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW3_MUXBusCtrl_ADDR;
// CSDSW3 Shadow defines
//   CSDSW3_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW3_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW4 address and mask defines
#pragma	ioport	CSDSW4_Data_ADDR:	0x8
BYTE			CSDSW4_Data_ADDR;
#pragma	ioport	CSDSW4_DriveMode_0_ADDR:	0x108
BYTE			CSDSW4_DriveMode_0_ADDR;
#pragma	ioport	CSDSW4_DriveMode_1_ADDR:	0x109
BYTE			CSDSW4_DriveMode_1_ADDR;
#pragma	ioport	CSDSW4_DriveMode_2_ADDR:	0xb
BYTE			CSDSW4_DriveMode_2_ADDR;
#pragma	ioport	CSDSW4_GlobalSelect_ADDR:	0xa
BYTE			CSDSW4_GlobalSelect_ADDR;
#pragma	ioport	CSDSW4_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW4_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW4_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW4_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW4_IntEn_ADDR:	0x9
BYTE			CSDSW4_IntEn_ADDR;
#define CSDSW4_MASK 0x10
#pragma	ioport	CSDSW4_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW4_MUXBusCtrl_ADDR;
// CSDSW4 Shadow defines
//   CSDSW4_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW4_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW5 address and mask defines
#pragma	ioport	CSDSW5_Data_ADDR:	0x8
BYTE			CSDSW5_Data_ADDR;
#pragma	ioport	CSDSW5_DriveMode_0_ADDR:	0x108
BYTE			CSDSW5_DriveMode_0_ADDR;
#pragma	ioport	CSDSW5_DriveMode_1_ADDR:	0x109
BYTE			CSDSW5_DriveMode_1_ADDR;
#pragma	ioport	CSDSW5_DriveMode_2_ADDR:	0xb
BYTE			CSDSW5_DriveMode_2_ADDR;
#pragma	ioport	CSDSW5_GlobalSelect_ADDR:	0xa
BYTE			CSDSW5_GlobalSelect_ADDR;
#pragma	ioport	CSDSW5_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW5_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW5_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW5_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW5_IntEn_ADDR:	0x9
BYTE			CSDSW5_IntEn_ADDR;
#define CSDSW5_MASK 0x20
#pragma	ioport	CSDSW5_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW5_MUXBusCtrl_ADDR;
// CSDSW5 Shadow defines
//   CSDSW5_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW5_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW6 address and mask defines
#pragma	ioport	CSDSW6_Data_ADDR:	0x8
BYTE			CSDSW6_Data_ADDR;
#pragma	ioport	CSDSW6_DriveMode_0_ADDR:	0x108
BYTE			CSDSW6_DriveMode_0_ADDR;
#pragma	ioport	CSDSW6_DriveMode_1_ADDR:	0x109
BYTE			CSDSW6_DriveMode_1_ADDR;
#pragma	ioport	CSDSW6_DriveMode_2_ADDR:	0xb
BYTE			CSDSW6_DriveMode_2_ADDR;
#pragma	ioport	CSDSW6_GlobalSelect_ADDR:	0xa
BYTE			CSDSW6_GlobalSelect_ADDR;
#pragma	ioport	CSDSW6_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW6_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW6_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW6_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW6_IntEn_ADDR:	0x9
BYTE			CSDSW6_IntEn_ADDR;
#define CSDSW6_MASK 0x40
#pragma	ioport	CSDSW6_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW6_MUXBusCtrl_ADDR;
// CSDSW6 Shadow defines
//   CSDSW6_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW6_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW7 address and mask defines
#pragma	ioport	CSDSW7_Data_ADDR:	0x8
BYTE			CSDSW7_Data_ADDR;
#pragma	ioport	CSDSW7_DriveMode_0_ADDR:	0x108
BYTE			CSDSW7_DriveMode_0_ADDR;
#pragma	ioport	CSDSW7_DriveMode_1_ADDR:	0x109
BYTE			CSDSW7_DriveMode_1_ADDR;
#pragma	ioport	CSDSW7_DriveMode_2_ADDR:	0xb
BYTE			CSDSW7_DriveMode_2_ADDR;
#pragma	ioport	CSDSW7_GlobalSelect_ADDR:	0xa
BYTE			CSDSW7_GlobalSelect_ADDR;
#pragma	ioport	CSDSW7_IntCtrl_0_ADDR:	0x10a
BYTE			CSDSW7_IntCtrl_0_ADDR;
#pragma	ioport	CSDSW7_IntCtrl_1_ADDR:	0x10b
BYTE			CSDSW7_IntCtrl_1_ADDR;
#pragma	ioport	CSDSW7_IntEn_ADDR:	0x9
BYTE			CSDSW7_IntEn_ADDR;
#define CSDSW7_MASK 0x80
#pragma	ioport	CSDSW7_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW7_MUXBusCtrl_ADDR;
// CSDSW7 Shadow defines
//   CSDSW7_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW7_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDResistor address and mask defines
#pragma	ioport	CSDResistor_Data_ADDR:	0xc
BYTE			CSDResistor_Data_ADDR;
#pragma	ioport	CSDResistor_DriveMode_0_ADDR:	0x10c
BYTE			CSDResistor_DriveMode_0_ADDR;
#pragma	ioport	CSDResistor_DriveMode_1_ADDR:	0x10d
BYTE			CSDResistor_DriveMode_1_ADDR;
#pragma	ioport	CSDResistor_DriveMode_2_ADDR:	0xf
BYTE			CSDResistor_DriveMode_2_ADDR;
#pragma	ioport	CSDResistor_GlobalSelect_ADDR:	0xe
BYTE			CSDResistor_GlobalSelect_ADDR;
#pragma	ioport	CSDResistor_IntCtrl_0_ADDR:	0x10e
BYTE			CSDResistor_IntCtrl_0_ADDR;
#pragma	ioport	CSDResistor_IntCtrl_1_ADDR:	0x10f
BYTE			CSDResistor_IntCtrl_1_ADDR;
#pragma	ioport	CSDResistor_IntEn_ADDR:	0xd
BYTE			CSDResistor_IntEn_ADDR;
#define CSDResistor_MASK 0x2
#pragma	ioport	CSDResistor_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDResistor_MUXBusCtrl_ADDR;
