/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// LED_BLUEPin address and mask defines
#pragma	ioport	LED_BLUEPin_Data_ADDR:	0x4
BYTE			LED_BLUEPin_Data_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_0_ADDR:	0x104
BYTE			LED_BLUEPin_DriveMode_0_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_1_ADDR:	0x105
BYTE			LED_BLUEPin_DriveMode_1_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_2_ADDR:	0x7
BYTE			LED_BLUEPin_DriveMode_2_ADDR;
#pragma	ioport	LED_BLUEPin_GlobalSelect_ADDR:	0x6
BYTE			LED_BLUEPin_GlobalSelect_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_BLUEPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_BLUEPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_BLUEPin_IntEn_ADDR:	0x5
BYTE			LED_BLUEPin_IntEn_ADDR;
#define LED_BLUEPin_MASK 0x4
#pragma	ioport	LED_BLUEPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_BLUEPin_MUXBusCtrl_ADDR;
// LED_BLUEPin Shadow defines
//   LED_BLUEPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_BLUEPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_REDPin address and mask defines
#pragma	ioport	LED_REDPin_Data_ADDR:	0x4
BYTE			LED_REDPin_Data_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_0_ADDR:	0x104
BYTE			LED_REDPin_DriveMode_0_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_1_ADDR:	0x105
BYTE			LED_REDPin_DriveMode_1_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_2_ADDR:	0x7
BYTE			LED_REDPin_DriveMode_2_ADDR;
#pragma	ioport	LED_REDPin_GlobalSelect_ADDR:	0x6
BYTE			LED_REDPin_GlobalSelect_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_REDPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_REDPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_REDPin_IntEn_ADDR:	0x5
BYTE			LED_REDPin_IntEn_ADDR;
#define LED_REDPin_MASK 0x8
#pragma	ioport	LED_REDPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_REDPin_MUXBusCtrl_ADDR;
// LED_REDPin Shadow defines
//   LED_REDPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_REDPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_GREENPin address and mask defines
#pragma	ioport	LED_GREENPin_Data_ADDR:	0x4
BYTE			LED_GREENPin_Data_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_0_ADDR:	0x104
BYTE			LED_GREENPin_DriveMode_0_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_1_ADDR:	0x105
BYTE			LED_GREENPin_DriveMode_1_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_2_ADDR:	0x7
BYTE			LED_GREENPin_DriveMode_2_ADDR;
#pragma	ioport	LED_GREENPin_GlobalSelect_ADDR:	0x6
BYTE			LED_GREENPin_GlobalSelect_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_GREENPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_GREENPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_GREENPin_IntEn_ADDR:	0x5
BYTE			LED_GREENPin_IntEn_ADDR;
#define LED_GREENPin_MASK 0x10
#pragma	ioport	LED_GREENPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_GREENPin_MUXBusCtrl_ADDR;
// LED_GREENPin Shadow defines
//   LED_GREENPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_GREENPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
