/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// AnalogColumn_InputMUX_1 address and mask defines
#pragma	ioport	AnalogColumn_InputMUX_1_Data_ADDR:	0x0
BYTE			AnalogColumn_InputMUX_1_Data_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_DriveMode_0_ADDR:	0x100
BYTE			AnalogColumn_InputMUX_1_DriveMode_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_DriveMode_1_ADDR:	0x101
BYTE			AnalogColumn_InputMUX_1_DriveMode_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_DriveMode_2_ADDR:	0x3
BYTE			AnalogColumn_InputMUX_1_DriveMode_2_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_GlobalSelect_ADDR:	0x2
BYTE			AnalogColumn_InputMUX_1_GlobalSelect_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_IntCtrl_0_ADDR:	0x102
BYTE			AnalogColumn_InputMUX_1_IntCtrl_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_IntCtrl_1_ADDR:	0x103
BYTE			AnalogColumn_InputMUX_1_IntCtrl_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_IntEn_ADDR:	0x1
BYTE			AnalogColumn_InputMUX_1_IntEn_ADDR;
#define AnalogColumn_InputMUX_1_MASK 0x40
#pragma	ioport	AnalogColumn_InputMUX_1_MUXBusCtrl_ADDR:	0x1d8
BYTE			AnalogColumn_InputMUX_1_MUXBusCtrl_ADDR;
// LED_BLUEPin address and mask defines
#pragma	ioport	LED_BLUEPin_Data_ADDR:	0x4
BYTE			LED_BLUEPin_Data_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_0_ADDR:	0x104
BYTE			LED_BLUEPin_DriveMode_0_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_1_ADDR:	0x105
BYTE			LED_BLUEPin_DriveMode_1_ADDR;
#pragma	ioport	LED_BLUEPin_DriveMode_2_ADDR:	0x7
BYTE			LED_BLUEPin_DriveMode_2_ADDR;
#pragma	ioport	LED_BLUEPin_GlobalSelect_ADDR:	0x6
BYTE			LED_BLUEPin_GlobalSelect_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_BLUEPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_BLUEPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_BLUEPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_BLUEPin_IntEn_ADDR:	0x5
BYTE			LED_BLUEPin_IntEn_ADDR;
#define LED_BLUEPin_MASK 0x4
#pragma	ioport	LED_BLUEPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_BLUEPin_MUXBusCtrl_ADDR;
// LED_BLUEPin Shadow defines
//   LED_BLUEPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_BLUEPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_REDPin address and mask defines
#pragma	ioport	LED_REDPin_Data_ADDR:	0x4
BYTE			LED_REDPin_Data_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_0_ADDR:	0x104
BYTE			LED_REDPin_DriveMode_0_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_1_ADDR:	0x105
BYTE			LED_REDPin_DriveMode_1_ADDR;
#pragma	ioport	LED_REDPin_DriveMode_2_ADDR:	0x7
BYTE			LED_REDPin_DriveMode_2_ADDR;
#pragma	ioport	LED_REDPin_GlobalSelect_ADDR:	0x6
BYTE			LED_REDPin_GlobalSelect_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_REDPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_REDPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_REDPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_REDPin_IntEn_ADDR:	0x5
BYTE			LED_REDPin_IntEn_ADDR;
#define LED_REDPin_MASK 0x8
#pragma	ioport	LED_REDPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_REDPin_MUXBusCtrl_ADDR;
// LED_REDPin Shadow defines
//   LED_REDPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_REDPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_GREENPin address and mask defines
#pragma	ioport	LED_GREENPin_Data_ADDR:	0x4
BYTE			LED_GREENPin_Data_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_0_ADDR:	0x104
BYTE			LED_GREENPin_DriveMode_0_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_1_ADDR:	0x105
BYTE			LED_GREENPin_DriveMode_1_ADDR;
#pragma	ioport	LED_GREENPin_DriveMode_2_ADDR:	0x7
BYTE			LED_GREENPin_DriveMode_2_ADDR;
#pragma	ioport	LED_GREENPin_GlobalSelect_ADDR:	0x6
BYTE			LED_GREENPin_GlobalSelect_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_0_ADDR:	0x106
BYTE			LED_GREENPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_GREENPin_IntCtrl_1_ADDR:	0x107
BYTE			LED_GREENPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_GREENPin_IntEn_ADDR:	0x5
BYTE			LED_GREENPin_IntEn_ADDR;
#define LED_GREENPin_MASK 0x10
#pragma	ioport	LED_GREENPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_GREENPin_MUXBusCtrl_ADDR;
// LED_GREENPin Shadow defines
//   LED_GREENPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_GREENPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2CsSDA address and mask defines
#pragma	ioport	EzI2CsSDA_Data_ADDR:	0x4
BYTE			EzI2CsSDA_Data_ADDR;
#pragma	ioport	EzI2CsSDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2CsSDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2CsSDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2CsSDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2CsSDA_DriveMode_2_ADDR:	0x7
BYTE			EzI2CsSDA_DriveMode_2_ADDR;
#pragma	ioport	EzI2CsSDA_GlobalSelect_ADDR:	0x6
BYTE			EzI2CsSDA_GlobalSelect_ADDR;
#pragma	ioport	EzI2CsSDA_IntCtrl_0_ADDR:	0x106
BYTE			EzI2CsSDA_IntCtrl_0_ADDR;
#pragma	ioport	EzI2CsSDA_IntCtrl_1_ADDR:	0x107
BYTE			EzI2CsSDA_IntCtrl_1_ADDR;
#pragma	ioport	EzI2CsSDA_IntEn_ADDR:	0x5
BYTE			EzI2CsSDA_IntEn_ADDR;
#define EzI2CsSDA_MASK 0x20
#pragma	ioport	EzI2CsSDA_MUXBusCtrl_ADDR:	0x1d9
BYTE			EzI2CsSDA_MUXBusCtrl_ADDR;
// EzI2CsSDA Shadow defines
//   EzI2CsSDA_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2CsSDA_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2CsSCL address and mask defines
#pragma	ioport	EzI2CsSCL_Data_ADDR:	0x4
BYTE			EzI2CsSCL_Data_ADDR;
#pragma	ioport	EzI2CsSCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2CsSCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2CsSCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2CsSCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2CsSCL_DriveMode_2_ADDR:	0x7
BYTE			EzI2CsSCL_DriveMode_2_ADDR;
#pragma	ioport	EzI2CsSCL_GlobalSelect_ADDR:	0x6
BYTE			EzI2CsSCL_GlobalSelect_ADDR;
#pragma	ioport	EzI2CsSCL_IntCtrl_0_ADDR:	0x106
BYTE			EzI2CsSCL_IntCtrl_0_ADDR;
#pragma	ioport	EzI2CsSCL_IntCtrl_1_ADDR:	0x107
BYTE			EzI2CsSCL_IntCtrl_1_ADDR;
#pragma	ioport	EzI2CsSCL_IntEn_ADDR:	0x5
BYTE			EzI2CsSCL_IntEn_ADDR;
#define EzI2CsSCL_MASK 0x80
#pragma	ioport	EzI2CsSCL_MUXBusCtrl_ADDR:	0x1d9
BYTE			EzI2CsSCL_MUXBusCtrl_ADDR;
// EzI2CsSCL Shadow defines
//   EzI2CsSCL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2CsSCL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSD_1SW0 address and mask defines
#pragma	ioport	CSD_1SW0_Data_ADDR:	0x8
BYTE			CSD_1SW0_Data_ADDR;
#pragma	ioport	CSD_1SW0_DriveMode_0_ADDR:	0x108
BYTE			CSD_1SW0_DriveMode_0_ADDR;
#pragma	ioport	CSD_1SW0_DriveMode_1_ADDR:	0x109
BYTE			CSD_1SW0_DriveMode_1_ADDR;
#pragma	ioport	CSD_1SW0_DriveMode_2_ADDR:	0xb
BYTE			CSD_1SW0_DriveMode_2_ADDR;
#pragma	ioport	CSD_1SW0_GlobalSelect_ADDR:	0xa
BYTE			CSD_1SW0_GlobalSelect_ADDR;
#pragma	ioport	CSD_1SW0_IntCtrl_0_ADDR:	0x10a
BYTE			CSD_1SW0_IntCtrl_0_ADDR;
#pragma	ioport	CSD_1SW0_IntCtrl_1_ADDR:	0x10b
BYTE			CSD_1SW0_IntCtrl_1_ADDR;
#pragma	ioport	CSD_1SW0_IntEn_ADDR:	0x9
BYTE			CSD_1SW0_IntEn_ADDR;
#define CSD_1SW0_MASK 0x1
#pragma	ioport	CSD_1SW0_MUXBusCtrl_ADDR:	0x1da
BYTE			CSD_1SW0_MUXBusCtrl_ADDR;
