//*****************************************************************************
//*****************************************************************************
//  FILENAME: CYFISNP_Time.h
//  Version: 2.00, Updated on 2015/3/4 at 22:21:19
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Star Network Protocol Time routnes header file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#ifndef CYFISNP_TIME_H
#define CYFISNP_TIME_H

#include <m8c.h>

void    CYFISNP_TimeSet     (WORD *pTimer, WORD time);
BOOL    CYFISNP_TimeExpired (WORD *pTimer);

#pragma fastcall16 CYFISNP_Delay100uS
void    CYFISNP_Delay100uS(void);

#define CYFISNP_TIMER_UNITS     16  // 16mS per Sleep Timer

#endif  // CYFISNP_TIME_H
// ###########################################################################
