//*****************************************************************************
//*****************************************************************************
//  FILENAME: CYFISNP_Debug.c
//  Version: 2.00, Updated on 2015/3/4 at 22:21:19
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: <NODE> Star Network Protocol Debugging routines
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


//--------------------------------------
// Included files
//--------------------------------------
#include "M8C.h"
#include "PSoCAPI.h"
#include "PSoCGPIOINT.h"


#if defined CYFISNP_DEBUG


void CYFISNP_OutChar(unsigned char data) {
//    volatile WORD delay;
//    if ( !(TX8_CONTROL_REG & TX8_TX_BUFFER_EMPTY)) {
//        while (!(TX8_CONTROL_REG & TX8_TX_COMPLETE)) {
//        }
//        for (delay = 0; delay < 50; ++delay);
//    }
//    TX8_TX_BUFFER_REG = data;
    TX8_PutChar(data);
}




//--------------------------------------
// Local Definitions and Types
//--------------------------------------
//--------------------------------------
// Local Function Declarations
//--------------------------------------

void CYFISNP_OutNibble(unsigned char nibble);


//--------------------------------------
// Local Definitions
//--------------------------------------


//void CYFISNP_OutChar(unsigned char data);

//--------------------------------------------------------------------------
//
//  Function:    CYFISNP_OutStr
//
//  Description: Writes a string to the serial port
//
//  Inputs:      uchar
//
//--------------------------------------------------------------------------
void CYFISNP_OutStr(const unsigned char *pbStrPtr)
{
    // loop for the null terminated string
    while ( *pbStrPtr != 0 )
    {
        // write a character
        CYFISNP_OutChar( *pbStrPtr );

        // point to the next character
        pbStrPtr++;
    }
}


//--------------------------------------------------------------------------
//
//  Function:    CYFISNP_OutStrData
//
//  Description: Writes a string to the serial port
//
//  Inputs:      uchar
//
//--------------------------------------------------------------------------
void CYFISNP_OutStrData(unsigned char *pbStrPtr)
{
    // loop for the null terminated string
    while ( *pbStrPtr != 0 )
    {
        // write a character
        CYFISNP_OutChar( *pbStrPtr );

        // point to the next character
        pbStrPtr++;
    }
}


//--------------------------------------------------------------------------
//
//  Function:    CYFISNP_OutHex
//
//  Description: Converts a byte to a hex value
//
//  Inputs:      Byte to be printed
//
//--------------------------------------------------------------------------
void CYFISNP_OutHex(unsigned char data)
{
    CYFISNP_OutNibble(data >> 4);
    CYFISNP_OutNibble(data);
}

//--------------------------------------------------------------------------
//
//  Function:    OutDec
//
//  Description: Converts both unsigned char and unsigned short to a decimal ascii value
//
//  Inputs:      Two byte or one byte value to be printed
//
//--------------------------------------------------------------------------
void OutDec(unsigned short u16DecByte)
{
    char decStr[6];
    unsigned char loop = 5;

    decStr[5] = '\0';

    while (loop)
    {
        // 22 code bytes cheaper here than in the while above
        --loop;

        decStr[loop] = (u16DecByte % 10) + '0';
        u16DecByte /= 10;

        if (u16DecByte == 0)
            break; // Kills leading zeros
    }

    CYFISNP_OutStrData(&decStr[loop]);
}


//--------------------------------------------------------------------------
//
//  Function:    OutSignedDec8
//
//  Description: Prints sign if necessary then calls OutDec
//
//  Inputs:      I8 - the value you want to print
//
//--------------------------------------------------------------------------
void OutSignedDec8(char decByte)
{
        if (decByte & 0x80)
        {
            CYFISNP_OutChar('-');
            decByte = 0 - decByte;
        }

        OutDec(decByte);
}


//--------------------------------------------------------------------------
//
//  Function:    CYFISNP_OutNibble
//
//  Description: Convert a nibble to an ASCII value
//
//  Inputs:      Byte to be printed in ASCII
//
//--------------------------------------------------------------------------
void CYFISNP_OutNibble(char nibble)
{
        nibble = nibble & 0x0F;

        if (nibble > 9)
        {
            nibble +=  ((char)'A' - 10);
        }
        else
        {
            nibble += '0';
        }

        CYFISNP_OutChar(nibble);
}

#endif // defined(DEBUG)
