/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "CYFISNP_Config.h"
#include "CYFISNP_Eeprom.h"
#include "CYFISNP_Private.h"
#include "CYFISNP_Protocol.h"
#include "CYFISNP_Time.h"
#include "CYFISNP.h"
#include "I2CMstr.h"
#include "I2CCommon.h"
#include "Timer8.h"

#endif
