//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_GREEN.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_GREEN User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_GREEN_INCLUDE
#define LED_GREEN_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_GREEN_Stop
#pragma fastcall16  LED_GREEN_Start
#pragma fastcall16  LED_GREEN_On
#pragma fastcall16  LED_GREEN_Off
#pragma fastcall16  LED_GREEN_Switch
#pragma fastcall16  LED_GREEN_Invert
#pragma fastcall16  LED_GREEN_GetState


//-------------------------------------------------
// Constants for LED_GREEN API's.
//-------------------------------------------------
//
#define  LED_GREEN_ON   1
#define  LED_GREEN_OFF  0

//-------------------------------------------------
// Prototypes of the LED_GREEN API.
//-------------------------------------------------
extern void  LED_GREEN_Start(void);                                     
extern void  LED_GREEN_Stop(void);                                      
extern void  LED_GREEN_On(void);                                      
extern void  LED_GREEN_Off(void);                                      
extern void  LED_GREEN_Switch(BYTE bSwitch);
extern void  LED_GREEN_Invert(void);                                         
extern BYTE  LED_GREEN_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
